name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run SemVer action
      uses: ./
      with:
        versioning: 'v1'
      id: semver
    - name: Handle incorrect version input
      if: ${{ steps.semver.outputs.version != '1.0.0' }}
      run: |
        echo expected 1.0.0 but got ${{ steps.semver.outputs.version }}
        exit 1
